spring:
  application:
    name: redaeri
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

server:
  port: 8080

jwt:
  secret:
    key: qltkdlemdnflxlaWkddlekdngkgkdjfakskzlfmfejsmffudigkfRk1


clova:
  api:
    key: ENC(9UcAhXAsO87Q4xfMwgfJ95nrnW4IxGcpZBFsLC0BflghBCMxJsYlQ/xxGWZQZioHauL/oNxOfpBxL6usXsKFzjHTQwwIlTlOzFmxZMhsD1A=)
  request:
    id: ENC(vmhTZV8TQtZoiBzrfj+5Sk/VU+6SSENrlZ+oV3WWIdGE9pfKOum962gjSPyMaTJiD74+FVhwJQz3+bBReR87ZGFaIFrJ1tXCVAsfWGxmFQo=)
  ocr:
    url: ENC(Kn5izFfJfu3ByYmEyeQcORLCZDw7PMwMRV3MeCfTfNktIo0s1hPB0cQdRH23rWfRHDHg/JtE8Sjza02l3sDrIYyVB+TvGeC7v/7A/zZs6OK4nDWdQZ/90tPwLP6Q9F2gNy9Be8G4zJsazkUtE7D3oSTq2OK8chtMbXbxUest4pi5nSu0YUDVyD246IKL9EiCwlJkMbtb7WPazuhPrIwdrA==)
    key: ENC(X2YCL9WSrof1H/Sn5pswlz4AOki3E5e2uS5hz7xayY+8KxrdGNOF872SklxKs1FvDxMNOKtftNf8qPm8tamL1gJWN9fjYdEo6zsK71WZRc4=)

kakao:
  client:
    id: ENC(ujSaVQKE3+lHeKn2Emjco4Xz560+IW7W3x1EhiktYiDuKfSg/bqyPeIw4x7L+/FdMExvhFNbyYKKd5jJYVnDru33XBeQha+Z0VBfMN+fClg=)

naver:
  client:
    id: ENC(ega5cdytiZomKKvFyW8G8nctn8DDA2jHdX6m/dQRnEHgODAJLbYrXnXVQjvhHBFC/GqAEaJOyMT3inwP5XyJrw==)
    key: ENC(yyfzJmigPwj35bpVIG5OUGAXCNUOBRwWVV1XcHC0wEx/gO3RG/fLkb11G7MzNORJ)

logging:
  config: classpath:log4j2.yml

mybatis:
  configuration:
    call-setters-on-nulls: true


---

spring:
  config:
    activate:
      on-profile:
      - local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.188.52.86:3306/redaeri?serverTimezone=UTC&characterEncoding=UTF-8
    username: ENC(at0vUhvo6SgjXkxjOulOdzXLUb1Pne8lAP+7ZR+GiPCQ2ha/lr9n/8NH7bJQ7M1x)
    password: ENC(bPrwxSJhPCW90gRJLxaK+JOji9ZVXxZabP1oDgzgUWLnfsv7361qpIwlnhqjbHsq)


---

spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://211.188.52.86:3306/redaeri?serverTimezone=UTC&characterEncoding=UTF-8
    username: ENC(at0vUhvo6SgjXkxjOulOdzXLUb1Pne8lAP+7ZR+GiPCQ2ha/lr9n/8NH7bJQ7M1x)
    password: ENC(bPrwxSJhPCW90gRJLxaK+JOji9ZVXxZabP1oDgzgUWLnfsv7361qpIwlnhqjbHsq)
