spring:
  application:
    name: redaeri
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


server:
  port: 8080

mybatis:
  mapper-locations: sql/*.xml
  configuration:
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로그 활성화



jwt:
  secret:
    key: qltkdlemdnflxlaWkddlekdngkgkdjfakskzlfmfejsmffudigkfRk1


clova:
  api:
    key: ENC(9UcAhXAsO87Q4xfMwgfJ95nrnW4IxGcpZBFsLC0BflghBCMxJsYlQ/xxGWZQZioHauL/oNxOfpBxL6usXsKFzjHTQwwIlTlOzFmxZMhsD1A=)
  request:
    id: ENC(vmhTZV8TQtZoiBzrfj+5Sk/VU+6SSENrlZ+oV3WWIdGE9pfKOum962gjSPyMaTJiD74+FVhwJQz3+bBReR87ZGFaIFrJ1tXCVAsfWGxmFQo=)

logging:
  level:
    root: INFO
    org.apache.ibatis: DEBUG  # MyBatis SQL 실행 로그

---

spring:
  config:
    activate:
      on-profile:
      - local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/redaeri?serverTimezone=UTC&characterEncoding=UTF-8
    username: ENC(ttOlbqf+jEsgiKszV/DrLFz7EqAGyGmRty5zBKQYPb42XRxX3BIkA7hMbIZi4XqZ)
    password: ENC(5O7so2/IIbHAxjsaYcV6H5fls9fy5xQ7Fj8U1ZuiLpojFM3nnDZ92J3+96OCWkfC)

---

spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(oA/nTK5Pn6v4SeNmCAGONe2hwcOH7MhQN8FiMVTwWxD0blBqOUzFL2sCHYN0m9ENIN/uvgTKzEvCoLidy9P0lCwmj8agRzRSrzP+UnRous+WwA0Rt7b8nLSLVS/B+/Z4yq4bKfSNgvMEePzIJMMbTQHdGiuxSLogURqZwk++Heg=)
    username: ENC(P6UNoqXzWUpPbNsHg28y26gzmBAse+Vh7GFN4tIfenWuAKsKM6+pSlz+YMMLkK2i)
    password: ENC(cdJ8XgTHfAqDhTDhZTW9Ayk55guy85G2lbczlxNHKlAPyw6L0DBjmhXjRArtFz3P)

